const demoProducts=[
 {id:1,name:'iPhone 15 Pro Max',cat:'Smartphones',state:'COMME NEUF',spec:'256 Go · Titane naturel · Batterie 92 %',price:620000,img:'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=900&q=85',battery:'92 %',color:'Titane naturel',storage:'256 Go',warranty:'6 mois'},
 {id:2,name:'MacBook Air M2',cat:'Ordinateurs',state:'TRÈS BON ÉTAT',spec:'8 Go · SSD 256 Go · 13 pouces',price:540000,img:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=85',color:'Gris sidéral',storage:'SSD 256 Go',warranty:'6 mois'},
 {id:3,name:'Samsung Galaxy S24',cat:'Smartphones',state:'NEUF',spec:'256 Go · Noir onyx · Garantie 12 mois',price:455000,img:'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=85',battery:'100 %',color:'Noir onyx',storage:'256 Go',warranty:'12 mois'},
 {id:4,name:'iPad Air M1',cat:'Tablettes',state:'RECONDITIONNÉ',spec:'64 Go · Wi‑Fi · Batterie contrôlée',price:310000,img:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=85',battery:'95 %',color:'Bleu',storage:'64 Go',warranty:'6 mois'},
 {id:5,name:'PlayStation 5 Slim',cat:'Gaming',state:'COMME NEUF',spec:'1 To · 1 manette · Boîte incluse',price:390000,img:'https://images.unsplash.com/photo-1606813902914-69e7d8d43fe3?auto=format&fit=crop&w=900&q=85',color:'Blanc',storage:'1 To',warranty:'6 mois'},
 {id:6,name:'AirPods Pro 2',cat:'Accessoires',state:'NEUF',spec:'USB‑C · Réduction de bruit active',price:155000,img:'https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?auto=format&fit=crop&w=900&q=85',color:'Blanc',storage:'—',warranty:'12 mois'}
];
let products=[];
const apiRoot=['okoumestore.find-gabon.com','127.0.0.1'].includes(location.hostname)?(location.hostname==='okoumestore.find-gabon.com'?'':'https://okoumestore.find-gabon.com'):'https://okoumestore.find-gabon.com';
const conditionLabels={neuf:'NEUF','comme-neuf':'COMME NEUF','tres-bon-etat':'TRÈS BON ÉTAT','bon-etat':'BON ÉTAT',reconditionne:'RECONDITIONNÉ'};
const mapProduct=p=>({id:p.id,name:p.name,cat:p.categories?.[0]?.name||'Électronique',state:conditionLabels[p.condition]||'OCCASION',spec:[p.meta?.storage,p.meta?.color,p.meta?.battery&&`Batterie ${p.meta.battery}`].filter(Boolean).join(' · '),price:p.price,regularPrice:p.regular_price,salePrice:p.sale_price,img:p.images?.[0]?.src||'/product-placeholder.svg',images:(p.images||[]).slice(0,10),battery:p.meta?.battery,color:p.meta?.color,storage:p.meta?.storage,warranty:p.meta?.warranty,accessories:p.meta?.accessories,controls:p.meta?.technical_controls,defects:p.meta?.defects});
async function loadProducts(){try{const res=await fetch(`${apiRoot}/wp-json/okoume/v1/products`);if(!res.ok)throw new Error();products=(await res.json()).map(mapProduct)}catch{products=[]}render()}
const cats=[['Smartphones','https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=80'],['Ordinateurs','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=700&q=80'],['Tablettes','https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=700&q=80'],['Gaming','https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=700&q=80']];
let cart=JSON.parse(localStorage.getItem('okoume-cart')||'[]');
const HOME_DELIVERY=2000;
const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
function save(){localStorage.setItem('okoume-cart',JSON.stringify(cart))}function go(path){location.hash=path;window.scrollTo(0,0)}
function header(){return `<header class="topbar"><div class="shell"><a class="brand" href="#/">OKO<b>U</b>MÉ</a><nav class="links"><a href="#/" class="active">Accueil</a><a href="#/catalogue">Boutique</a><a href="#/livraison">Livraison</a><a href="#/faq">FAQ</a><a href="#/compte">Compte</a><a href="#/contact">Contact</a></nav><div class="actions"><button class="search hide-mobile" aria-label="Rechercher">⌕</button><a class="icon-link" href="#/panier"><span class="icon">🛒</span><span class="hide-mobile">Panier</span><small>${cart.length||''}</small></a><a class="icon-link hide-mobile" href="#/suivi"><span class="icon">⌖</span>Suivi</a></div></div></header>`}
function footer(){return `<footer class="footer"><div class="shell"><div class="footer-grid"><div><a class="brand" href="#/">OKO<b>U</b>MÉ</a><p>L’électronique de confiance au Gabon. Appareils neufs et seconde main, contrôlés et garantis.</p><p>Libreville, Gabon<br/>Assistance WhatsApp : +241 77 63 88 64</p></div><div><h4>NAVIGATION</h4><a href="#/">Accueil</a><a href="#/catalogue">Boutique</a><a href="#/livraison">Livraison & Retrait</a><a href="#/a-propos">À propos</a></div><div><h4>INFORMATIONS</h4><a href="#/cgv">Conditions générales</a><a href="#/confidentialite">Confidentialité</a><a href="#/faq">FAQ</a><a href="#/suivi">Suivi de commande</a></div><div><h4>ARRIVAGES</h4><p>Recevez les nouveautés et bons plans sur WhatsApp.</p><div class="subscribe"><input placeholder="Numéro WhatsApp"><button>S’ABONNER</button></div></div></div><div class="copyright"><span>© OKOUMÉ 2026 — Électronique de confiance</span><span>Mentions légales · Confidentialité · Livraison</span></div></div></footer><nav class="mobile-nav"><a href="#/"><i>⌂</i>Accueil</a><a href="#/catalogue"><i>▦</i>Catalogue</a><a href="#/panier"><i>🛒</i>Panier</a><a href="#/suivi"><i>⌖</i>Suivi</a><a href="#/a-propos"><i>ⓘ</i>À propos</a></nav>`}
function card(p){return `<article class="product" onclick="go('/produit/${p.id}')"><div class="product-img"><img src="${p.img}" alt="${p.name}"><span class="badge ${p.state==='NEUF'?'good':''}">${p.state}</span>${p.salePrice?'<span class="sale-badge">PROMO</span>':''}</div><div class="product-info"><div class="product-cat">${p.cat}</div><h3>${p.name}</h3><div class="specs">${p.spec}</div><div class="price-row"><div><strong class="price">${money(p.price)}</strong>${p.salePrice?`<s class="old-price">${money(p.regularPrice)}</s>`:''}</div><button class="add" onclick="event.stopPropagation();add(${p.id})">Ajouter</button></div></div></article>`}
function home(){return `<main><section class="hero"><div class="shell"><div><span class="eyebrow">✦ APPAREILS CONTRÔLÉS & GARANTIS</span><h1>La technologie, <em>en toute confiance.</em></h1><p>Appareils neufs et seconde main certifiés. Livraison à domicile : 2 000 FCFA. Retrait OKOUMÉ gratuit.</p><div class="buttons"><a class="btn" href="#/catalogue">Voir la boutique&nbsp; →</a><a class="btn ghost" href="#/livraison">Livraison & Retrait</a></div></div><div class="hero-art"><div class="device-frame"><div class="device-screen"><div class="phone"></div></div></div></div></div></section><div class="ticker"><span>✦ NOUVEAUX ARRIVAGES CHAQUE SEMAINE &nbsp;&nbsp; • &nbsp;&nbsp; ✦ APPAREILS TESTÉS EN 32 POINTS &nbsp;&nbsp; • &nbsp;&nbsp; ✦ GARANTIE OKOUMÉ JUSQU’À 12 MOIS &nbsp;&nbsp; • &nbsp;&nbsp; ✦ LIVRAISON À DOMICILE : 2 000 FCFA &nbsp;&nbsp; • &nbsp;&nbsp;</span></div><div class="shell"><section class="perks"><div class="perk"><span class="icon">✓</span><h3>Appareils contrôlés</h3><p>Chaque occasion est vérifiée par nos techniciens avant mise en vente.</p></div><div class="perk"><span class="icon">♜</span><h3>Garantie OKOUMÉ</h3><p>Une garantie claire pour acheter en toute sérénité.</p></div><div class="perk"><span class="icon">⌖</span><h3>Livraison locale</h3><p>À domicile : 2 000 FCFA. Retrait gratuit en boutique OKOUMÉ.</p></div></section><section class="section"><div class="section-head"><div><h2>Nos Catégories</h2><p>Équipez-vous avec la technologie qui vous ressemble</p></div><a class="all-link" href="#/catalogue">Tout voir &nbsp;›</a></div><div class="category-grid">${cats.map(c=>`<a href="#/catalogue" class="category"><img src="${c[1]}" alt="${c[0]}"><span>${c[0]}</span></a>`).join('')}</div></section><section class="section"><div class="section-head"><div><h2>Offres du moment / Nouveautés</h2><p>Stocks limités, appareils disponibles immédiatement</p></div></div><div class="products">${products.slice(0,6).map(card).join('')}</div></section></div><section class="signup"><div class="shell signup-inner"><div><h2>Ne manquez pas les prochains arrivages</h2><p>Recevez nos nouveautés et bons plans directement sur WhatsApp.</p></div><div class="subscribe"><input placeholder="Votre numéro WhatsApp"><button>S’ABONNER</button></div></div></section></main>`}
function catalogue(){return `<main class="shell inner"><div class="crumb">Accueil / Boutique</div><h1 class="page-title">La boutique OKOUMÉ</h1><p style="color:var(--muted);margin:0">Neuf, occasion et reconditionné : trouvez l’appareil qui vous convient.</p><div class="catalogue-layout"><aside class="filters"><div class="filter"><h4>CATÉGORIES</h4>${['Smartphones','Ordinateurs','Tablettes','Gaming','Accessoires'].map(x=>`<label><input type="checkbox"> ${x}</label>`).join('')}</div><div class="filter"><h4>ÉTAT</h4>${['Neuf','Comme neuf','Très bon état','Bon état','Reconditionné'].map(x=>`<label><input type="checkbox"> ${x}</label>`).join('')}</div><div class="filter"><h4>PRIX</h4><label><input type="checkbox"> Moins de 200 000 FCFA</label><label><input type="checkbox"> 200 000 – 500 000 FCFA</label><label><input type="checkbox"> Plus de 500 000 FCFA</label></div></aside><div><div style="display:flex;justify-content:space-between;margin-bottom:18px;font-size:13px"><span>${products.length} appareils disponibles</span><span style="color:var(--muted)">Trier par : Nouveautés ▾</span></div><div class="products">${products.map(card).join('')}</div></div></div></main>`}
function product(id){let p=products.find(x=>x.id===+id);if(!p)return `<main class="shell inner"><div class="empty"><p>Ce produit n’est plus disponible.</p><a class="btn" href="#/catalogue">Retour à la boutique</a></div></main>`;return `<main class="shell inner"><div class="crumb"><a href="#/">Accueil</a> / <a href="#/catalogue">Boutique</a> / ${p.name}</div><div class="product-detail"><div class="gallery-main"><img src="${p.img}" alt="${p.name}"><span class="badge ${p.state==='NEUF'?'good':''}">${p.state}</span></div><div><div class="product-cat">${p.cat}</div><h1>${p.name}</h1><p class="specs" style="font-size:15px">${p.spec}</p><div class="detail-price">${money(p.price)}</div><div class="status">✓ En stock · Contrôlé par OKOUMÉ · Garantie incluse</div><div class="detail-list"><div><span>État</span><b>${p.state}</b></div><div><span>Stockage</span><b>${p.storage||'—'}</b></div><div><span>Couleur</span><b>${p.color||'—'}</b></div>${p.battery?`<div><span>Batterie</span><b>${p.battery}</b></div>`:''}<div><span>Garantie OKOUMÉ</span><b>${p.warranty||'À confirmer'}</b></div><div><span>Accessoires</span><b>${p.accessories||'Non renseignés'}</b></div><div><span>Contrôles techniques</span><b>${p.controls||'Non renseignés'}</b></div><div><span>Défauts éventuels</span><b>${p.defects||'Aucun défaut notable'}</b></div></div><div class="quantity"><button>−</button><span>1</span><button>+</button></div><button class="btn" onclick="add(${p.id})">Ajouter au panier&nbsp; →</button></div></div></main>`}
function add(id){if(!products.some(product=>product.id===id))return;cart.push(id);save();render();alert('Produit ajouté au panier.')}
function cartPage(){let rows=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);let total=rows.reduce((s,p)=>s+p.price,0);return `<main class="shell inner"><div class="crumb">Accueil / Panier</div><h1 class="page-title">Votre panier</h1>${rows.length?`<div class="cart-layout"><div>${rows.map(p=>`<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><div class="product-cat">${p.state} · ${p.cat}</div><h3 style="margin:6px 0;font:600 19px 'Space Grotesk'">${p.name}</h3><div class="specs">${p.spec}</div><b style="display:block;margin-top:13px">${money(p.price)}</b></div></div>`).join('')}</div><aside class="summary"><h3>Récapitulatif</h3><div><span>Sous-total</span><span>${money(total)}</span></div><div><span>Livraison à domicile</span><span>${money(HOME_DELIVERY)}</span></div><div class="total"><span>Total livraison incluse</span><span>${money(total+HOME_DELIVERY)}</span></div><p class="specs">Retrait en boutique OKOUMÉ : gratuit.</p><a class="btn" href="#/connexion">Passer la commande&nbsp; →</a></aside></div>`:`<div class="empty"><p>Votre panier est vide.</p><a class="btn" href="#/catalogue">Découvrir la boutique</a></div>`}</main>`}
function form(type){let checkout=type==='checkout';return `<main class="shell inner"><div class="form-wrap"><div class="crumb">Accueil / ${checkout?'Livraison & paiement':'Compte'}</div><div class="form-card"><h2>${checkout?'Livraison & paiement':'Connexion / Inscription'}</h2>${checkout?`<form onsubmit="checkout(event)"><div class="field"><label>MODE DE LIVRAISON</label><select id="delivery"><option value="home">Livraison à domicile — 2 000 FCFA</option><option value="pickup">Retrait gratuit — OKOUMÉ</option></select></div><p class="status">Livraison à domicile : 2 000 FCFA · Retrait en boutique : gratuit</p><div class="two-fields"><div class="field"><label>PRÉNOM</label><input id="firstName" required placeholder="Votre prénom"></div><div class="field"><label>NOM</label><input id="lastName" required placeholder="Votre nom"></div></div><div class="field"><label>ADRESSE DE LIVRAISON</label><input id="address" required placeholder="Quartier, rue, repère"></div><div class="field"><label>TÉLÉPHONE</label><input id="phone" required placeholder="+241"></div><div class="field"><label>PAIEMENT</label><select id="paymentMethod"><option value="cod">Paiement à la livraison</option><option value="airtel_money">Airtel Money — 077 638 864</option></select></div><p class="specs">Airtel Money : les instructions de règlement apparaîtront après la confirmation. Le paiement à la livraison reste disponible.</p><button class="btn" type="submit">Confirmer la commande&nbsp; →</button></form>`:`<form onsubmit="auth(event)"><div class="field"><label>ACCÈS</label><select id="authMode"><option value="login">Connexion</option><option value="register">Créer mon compte</option></select></div><div class="two-fields"><div class="field"><label>PRÉNOM</label><input id="authFirst" placeholder="Prénom"></div><div class="field"><label>NOM</label><input id="authLast" placeholder="Nom"></div></div><div class="field"><label>ADRESSE E-MAIL</label><input id="authEmail" required type="email" placeholder="vous@exemple.com"></div><div class="field"><label>MOT DE PASSE</label><input id="authPassword" required minlength="8" type="password" placeholder="8 caractères minimum"></div><button class="btn" type="submit">Continuer&nbsp; →</button><p style="font-size:13px;color:var(--muted);margin:18px 0 0">Votre compte vous permet de retrouver vos commandes et de commander plus vite.</p></form>`}</div></div></main>`}
async function auth(event){event.preventDefault();const action=document.querySelector('#authMode').value;const body={email:authEmail.value,password:authPassword.value,first_name:authFirst.value,last_name:authLast.value};const r=await fetch(`${apiRoot}/wp-json/okoume/v1/auth/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});if(!r.ok){const d=await r.json();return alert(d.message||'Impossible de continuer.')}sessionStorage.setItem('okoumeUser',JSON.stringify(await r.json()));go('/livraison')}
async function checkout(event){event.preventDefault();if(!cart.length)return go('/catalogue');const user=JSON.parse(sessionStorage.getItem('okoumeUser')||'{}');const body={items:cart.map(id=>({id,quantity:1})),delivery_method:delivery.value,payment_method:paymentMethod.value,billing:{first_name:firstName.value,last_name:lastName.value,email:user.email||'',phone:phone.value,address_1:address.value,city:delivery.value==='home'?'Livraison à domicile':'Retrait OKOUMÉ'}};const r=await fetch(`${apiRoot}/wp-json/okoume/v1/orders`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});if(!r.ok){const d=await r.json();return alert(d.message||'La commande n’a pas pu être créée.')}const order=await r.json();sessionStorage.setItem('okoumeOrder',order.number);sessionStorage.setItem('okoumeOrderTotal',order.total);sessionStorage.setItem('okoumePaymentMethod',paymentMethod.value);cart=[];save();if(order.redirect_url){location.href=order.redirect_url;return}go('/confirmation')}
function confirmation(){let ref=sessionStorage.getItem('okoumeOrder')||'—';let total=sessionStorage.getItem('okoumeOrderTotal');let payment=sessionStorage.getItem('okoumePaymentMethod');let instructions=payment==='airtel_money'?`<div class="status" style="text-align:left">Règlement Airtel Money<br><b>077 638 864</b>${total?`<br>Montant : <b>${money(total)}</b>`:''}<br>Indiquez la référence <b>${ref}</b> dans votre paiement. La commande sera validée après vérification.</div>`:'<div class="status">Paiement à la livraison : notre équipe vous contactera pour confirmer la livraison.</div>';return `<main class="shell inner"><div class="form-wrap"><div class="empty" style="padding:60px 30px"><div style="font-size:38px;color:var(--brand)">✓</div><h1 class="page-title" style="font-size:29px">Commande confirmée</h1><p>Votre commande a été créée dans le système OKOUMÉ.</p><p style="font:600 14px 'DM Mono'">RÉFÉRENCE : ${ref}</p>${instructions}<a class="btn" href="#/suivi">Suivre ma commande&nbsp; →</a></div></div></main>`}
function tracking(){return `<main class="shell inner"><div class="crumb">Accueil / Suivi de commande</div><h1 class="page-title">Suivi de commande</h1><div class="form-wrap" style="margin-left:0"><div class="form-card"><p style="line-height:1.7;color:var(--muted)">Saisissez votre référence de suivi OKOUMÉ.</p><form onsubmit="trackOrder(event)"><div class="field"><label>RÉFÉRENCE DE SUIVI</label><input id="trackingNumber" required placeholder="Ex. OZ-000173-GA-482731"></div><div class="field"><label>TÉLÉPHONE — ANCIENNES COMMANDES UNIQUEMENT</label><input id="trackingPhone" placeholder="Ex. 077 63 88 64"></div><button class="btn" type="submit">Rechercher</button></form><div id="trackingResult" aria-live="polite"></div></div></div></main>`}
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]));
async function trackOrder(event){event.preventDefault();const result=document.querySelector('#trackingResult');result.innerHTML='<p style="margin-top:20px;color:var(--muted)">Recherche de votre commande…</p>';try{const params=new URLSearchParams({number:trackingNumber.value,phone:trackingPhone.value});const response=await fetch(`${apiRoot}/wp-json/okoume/v1/orders/track?${params}`);const data=await response.json();if(!response.ok)throw new Error(data.message||'Commande introuvable.');result.innerHTML=`<div class="status" style="margin-top:20px"><b>Commande n° ${escapeHtml(data.number)}</b><br>${escapeHtml(data.status_label)}</div><p style="font-size:13px;color:var(--muted)">${data.items.map(item=>`${escapeHtml(item.name)} × ${item.quantity}`).join('<br>')}</p>`}catch(error){result.innerHTML=`<p style="margin-top:20px;color:var(--brand)">${escapeHtml(error.message)}</p>`}}
function basic(title,text){return `<main class="shell inner"><div class="crumb">Accueil / ${title}</div><h1 class="page-title">${title}</h1><div class="form-wrap" style="margin-left:0"><div class="form-card"><p style="line-height:1.7;color:var(--muted)">${text}</p></div></div></main>`}
function render(){let path=location.hash.slice(1)||'/';let content=path==='/'?home():path==='/catalogue'?catalogue():path.startsWith('/produit/')?product(path.split('/').pop()):path==='/panier'?cartPage():path==='/connexion'||path==='/compte'?form('login'):path==='/livraison'?form('checkout'):path==='/confirmation'?confirmation():path==='/suivi'?tracking():basic(path.slice(1).replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase()),'Retrouvez ici toutes les informations utiles concernant OKOUMÉ et vos achats.');document.querySelector('#app').innerHTML=header()+content+footer()}window.addEventListener('hashchange',render);render();loadProducts();
const okoumeWhatsApp='https://wa.me/24177638864';
function mountAssistant(){if(document.querySelector('#okoume-assistant'))return;document.body.insertAdjacentHTML('beforeend',`<section class="assistant" id="okoume-assistant" aria-label="Assistant OKOUMÉ"><button class="assistant-launch" onclick="toggleAssistant()">◌ <span>Besoin d’aide ?</span></button><div class="assistant-panel" hidden><div class="assistant-head"><strong>Assistant OKOUMÉ</strong><button onclick="toggleAssistant()" aria-label="Fermer">×</button></div><div class="assistant-body" id="assistantMessages"><p>Bonjour ! Je peux vous renseigner sur nos appareils, livraisons, garanties et commandes.</p></div><form class="assistant-form" onsubmit="askAssistant(event)"><input id="assistantQuestion" required placeholder="Votre question…"><input id="assistantEmail" type="email" placeholder="Votre e-mail si suivi nécessaire"><button type="submit">Envoyer</button></form></div></section>`)}
function toggleAssistant(){const panel=document.querySelector('.assistant-panel');panel.hidden=!panel.hidden}
async function askAssistant(event){event.preventDefault();const question=document.querySelector('#assistantQuestion');const email=document.querySelector('#assistantEmail');const messages=document.querySelector('#assistantMessages');messages.insertAdjacentHTML('beforeend',`<p class="visitor">${question.value.replace(/[<>]/g,'')}</p>`);const r=await fetch(`${apiRoot}/wp-json/okoume/v1/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question.value,email:email.value})});const data=await r.json();messages.insertAdjacentHTML('beforeend',`<p>${data.answer||'Notre équipe revient vers vous rapidement.'}</p>`);question.value='';messages.scrollTop=messages.scrollHeight}
document.addEventListener('click',event=>{if(event.target.closest('.subscribe button'))location.href=okoumeWhatsApp});
function mountProductGallery(){const path=location.hash.slice(1);if(!path.startsWith('/produit/'))return;const product=products.find(item=>item.id===+path.split('/').pop());const gallery=document.querySelector('.gallery-main');if(!product||!gallery||gallery.dataset.ready||product.images.length<2)return;gallery.dataset.ready='true';const image=gallery.querySelector('img');image.id='product-main-image';const thumbs=document.createElement('div');thumbs.className='gallery-thumbs';product.images.forEach((photo,index)=>{const button=document.createElement('button');button.type='button';button.className=`gallery-thumb${index===0?' active':''}`;button.setAttribute('aria-label',`Voir la photo ${index+1} de ${product.name}`);const thumb=document.createElement('img');thumb.src=photo.src;thumb.alt='';button.appendChild(thumb);button.addEventListener('click',()=>{image.src=photo.src;image.alt=photo.alt||product.name;thumbs.querySelectorAll('.gallery-thumb').forEach(item=>item.classList.remove('active'));button.classList.add('active')});thumbs.appendChild(button)});gallery.insertAdjacentElement('afterend',thumbs)}
new MutationObserver(mountProductGallery).observe(document.querySelector('#app'),{childList:true,subtree:true});
function trustMarkup(kind='standard'){const items=`<article class="trust-item"><i aria-hidden="true">⇢</i><div><b>Livraison à domicile</b><span>2 000 FCFA partout à Libreville</span></div></article><article class="trust-item"><i aria-hidden="true">▣</i><div><b>Paiement sécurisé</b><span>Carte via Stripe</span></div></article><article class="trust-item"><i aria-hidden="true">◉</i><div><b>Airtel Money</b><span>Paiement vérifié</span></div></article><article class="trust-item"><i aria-hidden="true">⌖</i><div><b>Commande suivie</b><span>Suivez votre référence OKOUMÉ</span></div></article>`;return `<section class="trust-strip ${kind==='footer'?'footer-trust':kind==='hero'?'hero-trust':kind==='product'?'compact':''}" data-trust="${kind}" aria-label="Acheter en confiance"><div class="trust-items">${items}</div></section>`}
function mountTrustSignals(){const footer=document.querySelector('.footer-grid');if(footer&&!footer.parentElement.querySelector('[data-trust="footer"]'))footer.insertAdjacentHTML('afterend',trustMarkup('footer'));const path=location.hash.slice(1)||'/';if(path==='/'){const buttons=document.querySelector('.hero .buttons');if(buttons&&!buttons.parentElement.querySelector('[data-trust="hero"]'))buttons.insertAdjacentHTML('afterend',trustMarkup('hero'))}if(path.startsWith('/produit/')){const detail=document.querySelector('.purchase-column')||document.querySelector('.product-detail > div:last-child');const price=detail?.querySelector('.detail-price');if(detail&&!detail.querySelector('[data-trust="product"]'))(price||detail).insertAdjacentHTML(price?'afterend':'beforeend',trustMarkup('product'))}}
new MutationObserver(mountTrustSignals).observe(document.querySelector('#app'),{childList:true,subtree:true});
function mountStripeCardOption(){const select=document.querySelector('#paymentMethod');if(select&&!select.querySelector('option[value="stripe"]')){const option=document.createElement('option');option.value='stripe';option.textContent='Carte bancaire sécurisée — Stripe';select.appendChild(option)}if((location.hash||'').startsWith('#/confirmation')&&sessionStorage.getItem('okoumePaymentMethod')==='stripe'){const status=document.querySelector('.empty .status');if(status)status.innerHTML='Paiement carte sécurisé par Stripe. Votre commande est confirmée après validation du paiement.'}}
new MutationObserver(mountStripeCardOption).observe(document.querySelector('#app'),{childList:true,subtree:true});
async function verifyStripeReturn(){const sessionId=new URLSearchParams(location.search).get('stripe_session_id');if(!sessionId)return;try{const response=await fetch(`${apiRoot}/wp-json/okoume/v1/stripe/return?session_id=${encodeURIComponent(sessionId)}`);const payment=await response.json();if(!response.ok||!payment.paid)throw new Error();sessionStorage.setItem('okoumeOrder',payment.number);sessionStorage.setItem('okoumeOrderTotal',payment.total);sessionStorage.setItem('okoumePaymentMethod','stripe');history.replaceState({},'',location.pathname+location.hash);render()}catch{alert('Le paiement est en cours de vérification. Vous pourrez suivre votre commande dans quelques instants.')}}
verifyStripeReturn();
mountAssistant();

conditionLabels['bonne-occasion']='BONNE OCCASION';
function restockMarkup(product){return `<section class="restock-box"><h3>Produit momentanément indisponible</h3><p>Laissez votre numéro WhatsApp : OKOUMÉ vous préviendra dès que <b>${product.name}</b> sera de nouveau disponible.</p><form onsubmit="requestRestock(event,${product.id})"><input type="tel" name="phone" required inputmode="tel" placeholder="Votre numéro WhatsApp"><button type="submit">M’avertir du retour</button></form><small>Votre numéro est utilisé uniquement pour cette alerte de disponibilité.</small></section>`}
async function requestRestock(event,productId){event.preventDefault();const form=event.currentTarget;const button=form.querySelector('button');button.disabled=true;try{const response=await fetch(`${apiRoot}/wp-json/okoume/v1/restock`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,phone:new FormData(form).get('phone')})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Impossible d’enregistrer la demande.');form.outerHTML=`<p class="restock-success">✓ ${data.message}</p>`}catch(error){alert(error.message);button.disabled=false}}
function mountAvailability(){const path=location.hash.slice(1)||'/';if(path.startsWith('/produit/')){const current=products.find(item=>item.id===+path.split('/').pop());const detail=document.querySelector('.product-detail > div:last-child');if(current&&detail&&!current.inStock&&!detail.querySelector('.restock-box')){const status=detail.querySelector('.status');if(status){status.textContent='Indisponible · Alerte de retour disponible';status.classList.add('stock-out-status')}detail.querySelector('.quantity')?.remove();const buy=detail.querySelector('button.btn');if(buy)buy.replaceWith(document.createRange().createContextualFragment(restockMarkup(current)));}}
document.querySelectorAll('.product').forEach(card=>{const match=card.getAttribute('onclick')?.match(/\/(\d+)/);const current=match&&products.find(item=>item.id===+match[1]);if(current&&!current.inStock&&!card.dataset.stockReady){card.dataset.stockReady='true';const badge=card.querySelector('.badge');if(badge){badge.textContent='RUPTURE';badge.classList.add('stock-out-badge')}const add=card.querySelector('.add');if(add){add.textContent='Indisponible';add.disabled=true;add.classList.add('stock-out-button')}}})}
new MutationObserver(mountAvailability).observe(document.querySelector('#app'),{childList:true,subtree:true});
loadProducts=async function(){try{const res=await fetch(`${apiRoot}/wp-json/okoume/v1/products`);if(!res.ok)throw new Error();products=(await res.json()).map(product=>({...mapProduct(product),inStock:product.stock_status==='instock',stockQuantity:product.stock_quantity===null?null:Math.max(0,Number(product.stock_quantity)||0)}))}catch{products=[]}render()};
loadProducts();

function searchPage(){return `<main class="shell inner"><div class="crumb">Accueil / Recherche</div><h1 class="page-title">Rechercher un appareil</h1><div class="catalog-search"><label for="catalogueSearch">Nom, marque ou catégorie</label><div><input id="catalogueSearch" type="search" placeholder="Ex. Samsung, Sony, routeur…" oninput="searchCatalogue()"><button onclick="searchCatalogue()">Rechercher</button></div></div><p id="searchCount" class="specs">Saisissez votre recherche pour parcourir le catalogue.</p><div id="searchResults" class="products"></div></main>`}
function searchCatalogue(){const input=document.querySelector('#catalogueSearch');const results=document.querySelector('#searchResults');const count=document.querySelector('#searchCount');if(!input||!results)return;const query=input.value.trim().toLocaleLowerCase('fr');const found=products.filter(product=>`${product.name} ${product.cat} ${product.state} ${product.spec}`.toLocaleLowerCase('fr').includes(query));count.textContent=query?`${found.length} appareil${found.length>1?'s':''} trouvé${found.length>1?'s':''}.`:'Saisissez votre recherche pour parcourir le catalogue.';results.innerHTML=query?found.map(card).join(''):'';mountAvailability()}
function contactPage(){return `<main class="shell inner"><div class="crumb">Accueil / Contact</div><div class="form-wrap" style="margin-left:0"><div class="form-card"><h1 class="page-title">Nous contacter</h1><p class="specs">Une question avant ou après votre achat ? Écrivez-nous, l’équipe OKOUMÉ répondra à votre e-mail.</p><form onsubmit="sendContact(event)"><div class="field"><label>NOM</label><input name="name" required autocomplete="name" placeholder="Votre nom"></div><div class="field"><label>ADRESSE E-MAIL</label><input name="email" required type="email" autocomplete="email" placeholder="vous@exemple.com"></div><div class="field"><label>OBJET</label><input name="subject" required placeholder="Votre demande"></div><div class="field"><label>MESSAGE</label><textarea name="message" required minlength="10" rows="6" placeholder="Comment pouvons-nous vous aider ?"></textarea></div><button class="btn" type="submit">Envoyer le message&nbsp; →</button><p id="contactResult" class="form-result" aria-live="polite"></p></form></div></div></main>`}
async function sendContact(event){event.preventDefault();const form=event.currentTarget;const result=form.querySelector('#contactResult');const button=form.querySelector('button');button.disabled=true;result.textContent='Envoi en cours…';try{const payload=Object.fromEntries(new FormData(form));const response=await fetch(`${apiRoot}/wp-json/okoume/v1/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Impossible d’envoyer le message.');result.textContent=data.message;result.className='form-result success';form.reset()}catch(error){result.textContent=error.message+' Vous pouvez aussi écrire à info@find-gabon.com.';result.className='form-result error'}finally{button.disabled=false}}
askAssistant=async function(event){event.preventDefault();const question=document.querySelector('#assistantQuestion');const email=document.querySelector('#assistantEmail');const messages=document.querySelector('#assistantMessages');const value=question.value.trim();if(!value)return;messages.insertAdjacentHTML('beforeend',`<p class="visitor">${value.replace(/[<>]/g,'')}</p>`);question.value='';try{const response=await fetch(`${apiRoot}/wp-json/okoume/v1/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value,email:email.value})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Le service est indisponible.');messages.insertAdjacentHTML('beforeend',`<p>${String(data.answer||'Notre équipe revient vers vous rapidement.').replace(/[<>]/g,'')}</p>`)}catch(error){messages.insertAdjacentHTML('beforeend',`<p>Je n’ai pas pu transmettre votre demande. Écrivez-nous à <a href="mailto:info@find-gabon.com">info@find-gabon.com</a> ou sur WhatsApp au 077 638 864.</p>`)}messages.scrollTop=messages.scrollHeight}
const previousRender=render;
render=function(){previousRender();const path=location.hash.slice(1)||'/';if(path==='/recherche'||path==='/contact'){document.querySelector('#app').innerHTML=header()+(path==='/recherche'?searchPage():contactPage())+footer();}}
document.addEventListener('click',event=>{if(event.target.closest('.search')){event.preventDefault();go('/recherche')}});

let deferredInstallPrompt;
/* Navigation uses in-place skeletons instead of an opaque loading screen. */
function showLoader(){return false}
function hideLoader(){return false}
function mountCartCount(){const link=document.querySelector('.mobile-nav a[href="#/panier"]');if(!link)return;let count=link.querySelector('.mobile-cart-count');if(!count){count=document.createElement('small');count.className='mobile-cart-count';link.appendChild(count)}count.textContent=cart.length?String(cart.length):'';count.hidden=!cart.length}
function mountInstallPrompt(){if(!deferredInstallPrompt||document.querySelector('#install-okoume'))return;document.body.insertAdjacentHTML('beforeend','<button id="install-okoume" class="install-pwa" type="button">Installer OKOUMÉ</button>');document.querySelector('#install-okoume').addEventListener('click',async()=>{const button=document.querySelector('#install-okoume');deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;button.remove()})}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;mountInstallPrompt()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;document.querySelector('#install-okoume')?.remove()});
function accountPage(){return `<main class="shell inner"><div class="form-wrap"><div class="crumb">Accueil / Compte</div><div class="form-card"><div class="account-tabs"><button type="button" class="active" onclick="setAccountMode('login')">Connexion</button><button type="button" onclick="setAccountMode('register')">Inscription</button></div><div id="phoneAccountForm"></div></div></div></main>`}
function setAccountMode(mode){const target=document.querySelector('#phoneAccountForm');if(!target)return;target.innerHTML=mode==='register'?`<h2>Créer mon compte</h2><p class="specs">Créez votre accès pour retrouver vos commandes et accélérer vos prochains achats.</p><form onsubmit="phoneAuth(event,'register')"><div class="two-fields"><div class="field"><label>PRÉNOM</label><input name="first_name" required autocomplete="given-name" placeholder="Votre prénom"></div><div class="field"><label>NOM</label><input name="last_name" required autocomplete="family-name" placeholder="Votre nom"></div></div><div class="field"><label>NUMÉRO DE TÉLÉPHONE</label><input name="phone" required inputmode="tel" autocomplete="tel" placeholder="077 63 88 64"></div><div class="field"><label>ADRESSE E-MAIL</label><input name="email" required type="email" autocomplete="email" placeholder="vous@exemple.com"></div><div class="field"><label>ADRESSE DE LIVRAISON</label><input name="address" required autocomplete="street-address" placeholder="Quartier, rue, repère précis"></div><div class="field"><label>MOT DE PASSE</label><input name="password" required minlength="12" type="password" autocomplete="new-password" placeholder="12 caractères minimum"></div><div class="field"><label>CONFIRMER LE MOT DE PASSE</label><input name="password_confirmation" required minlength="12" type="password" autocomplete="new-password" placeholder="Retapez votre mot de passe"></div><button class="btn" type="submit">Créer mon compte&nbsp; →</button><p id="accountResult" class="form-result" aria-live="polite"></p></form>`:`<h2>Connexion</h2><p class="specs">Connectez-vous avec le numéro utilisé lors de votre inscription.</p><form onsubmit="phoneAuth(event,'login')"><div class="field"><label>NUMÉRO DE TÉLÉPHONE</label><input name="phone" required inputmode="tel" autocomplete="tel" placeholder="077 63 88 64"></div><div class="field"><label>MOT DE PASSE</label><input name="password" required type="password" autocomplete="current-password" placeholder="Votre mot de passe"></div><button class="btn" type="submit">Se connecter&nbsp; →</button><p id="accountResult" class="form-result" aria-live="polite"></p></form>`;document.querySelectorAll('.account-tabs button').forEach(button=>button.classList.toggle('active',button.textContent.toLowerCase().startsWith(mode==='login'?'connexion':'inscription')))}
async function phoneAuth(event,action){event.preventDefault();const form=event.currentTarget;const result=form.querySelector('#accountResult');const button=form.querySelector('button');const data=Object.fromEntries(new FormData(form));if(action==='register'&&data.password!==data.password_confirmation){result.textContent='Les deux mots de passe ne correspondent pas.';result.className='form-result error';return}button.disabled=true;showLoader(action==='login'?'Connexion sécurisée…':'Création du compte…');try{const response=await fetch(`${apiRoot}/wp-json/okoume/v1/auth/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(data)});const responseData=await response.json();if(!response.ok)throw new Error(responseData.message||'Impossible de continuer.');sessionStorage.setItem('okoumeUser',JSON.stringify(responseData));go('/livraison')}catch(error){result.textContent=error.message;result.className='form-result error'}finally{button.disabled=false;hideLoader()}}
const appRenderWithPages=render;
render=function(){showLoader();appRenderWithPages();const path=location.hash.slice(1)||'/';if(path==='/compte'||path==='/connexion'){document.querySelector('#app').innerHTML=header()+accountPage()+footer();setAccountMode('login')}mountCartCount();mountInstallPrompt()};
const productsLoader=loadProducts;
loadProducts=async function(){showLoader('Mise à jour de la boutique…');try{await productsLoader()}finally{hideLoader();mountCartCount()}};

const routeTransitionMs=900;
const originalGo=go;
go=function(path){showLoader('Ouverture de votre page…');document.querySelector('#app')?.classList.add('page-leaving');setTimeout(()=>originalGo(path),180)};
const renderWithLoader=render;
render=function(){const started=Date.now();showLoader('Chargement…');renderWithLoader();document.querySelector('#app')?.classList.remove('page-leaving');document.querySelector('#app')?.classList.add('page-entering');mountContentSkeletons();mountCartCount();setTimeout(()=>{document.querySelector('#app')?.classList.remove('page-entering');hideLoader()},Math.max(120,routeTransitionMs-(Date.now()-started)))};
function mountContentSkeletons(){if(products.length)return;const path=location.hash.slice(1)||'/';if(!['/','/catalogue','/panier','/suivi','/compte','/connexion'].some(route=>path===route))return;const target=document.querySelector('.products')||document.querySelector('.form-card')||document.querySelector('.summary');if(target&&!target.querySelector('.skeleton-grid'))target.insertAdjacentHTML('beforeend','<div class="skeleton-grid" aria-label="Chargement du contenu"><i></i><i></i><i></i></div>')}
const originalSetAccountMode=setAccountMode;
setAccountMode=function(mode){originalSetAccountMode(mode);if(mode==='login'){const form=document.querySelector('#phoneAccountForm form');if(form&&!form.querySelector('.forgot-password'))form.insertAdjacentHTML('beforeend','<a class="forgot-password" href="#/contact">Mot de passe oublié ?</a>')}};
function pwaDismissed(){return Number(localStorage.getItem('okoume-install-dismissed')||0)>Date.now()-7*24*60*60*1000}
mountInstallPrompt=function(){if(document.querySelector('#install-okoume')||pwaDismissed()||window.matchMedia('(display-mode: standalone)').matches||navigator.standalone)return;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);if(!deferredInstallPrompt&&!ios)return;document.body.insertAdjacentHTML('beforeend',`<section id="install-okoume" class="install-pwa" aria-label="Installer l’application OKOUMÉ"><button class="install-close" aria-label="Fermer">×</button><div class="install-icon">OK</div><div><strong>OKOUMÉ, toujours à portée de main</strong><p>${ios?'Touchez Partager, puis « Sur l’écran d’accueil ».':'Installez l’application pour ouvrir la boutique plus vite et suivre vos commandes.'}</p><button class="install-action">${ios?'Voir les instructions':'Installer l’application'}</button></div></section>`);const panel=document.querySelector('#install-okoume');panel.querySelector('.install-close').addEventListener('click',()=>{localStorage.setItem('okoume-install-dismissed',String(Date.now()));panel.remove()});panel.querySelector('.install-action').addEventListener('click',async()=>{if(ios){panel.querySelector('p').textContent='Safari : touchez Partager, faites défiler puis choisissez « Sur l’écran d’accueil ».';return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;panel.remove()})};
setTimeout(mountInstallPrompt,900);

/* Skeleton states keep the page structure visible while the catalogue arrives. */
const cartPageWithSkeleton=cartPage;
cartPage=function(){if(!products.length&&cart.length)return `<main class="shell inner"><div class="crumb">Accueil / Panier</div><h1 class="page-title">Votre panier</h1><div class="cart-skeleton" aria-label="Chargement du panier"><i></i><i></i><aside><i></i><i></i><i></i></aside></div></main>`;return cartPageWithSkeleton()};
const productWithSkeleton=product;
product=function(id){if(!products.length)return `<main class="shell inner"><div class="product-skeleton" aria-label="Chargement du produit"><i></i><div><i></i><i></i><i></i><i></i></div></div></main>`;return productWithSkeleton(id)};

/* A local basket is allowed offline; placing an order is not. */
async function serverReachable(){if(!navigator.onLine)return false;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(`${apiRoot}/wp-json/okoume/v1/products`,{cache:'no-store',signal:controller.signal});return response.ok}catch{return false}finally{clearTimeout(timeout)}}
function mountOfflineState(){let banner=document.querySelector('#offline-status');if(!banner){document.body.insertAdjacentHTML('beforeend','<aside id="offline-status" class="offline-status" role="status" hidden>Vous êtes hors ligne. Votre panier est conservé, mais la commande nécessite une connexion.</aside>');banner=document.querySelector('#offline-status')}const apply=async()=>{const online=await serverReachable();banner.hidden=online;document.documentElement.classList.toggle('okoume-offline',!online);const submit=document.querySelector('form[onsubmit="checkout(event)"] button[type="submit"]');if(submit){submit.disabled=!online;submit.title=online?'':'Connexion requise pour finaliser la commande.'}};window.addEventListener('online',apply,{once:true});window.addEventListener('offline',apply,{once:true});apply()}
const checkoutWithConnectivity=checkout;
checkout=async function(event){if(!await serverReachable()){event.preventDefault();alert('Connexion requise pour finaliser votre commande. Vérifiez votre réseau puis réessayez.');mountOfflineState();return}return checkoutWithConnectivity(event)};
const renderWithOfflineState=render;
render=function(){renderWithOfflineState();mountOfflineState()};

/* Cart quantities are intentionally derived from the current catalogue.  The
   server repeats these checks during checkout; this only keeps the interface
   honest and prevents accidental duplicate additions. */
function cartQuantity(id){return cart.filter(item=>item===id).length}
function availableQuantity(product){return product&&product.stockQuantity!==null?product.stockQuantity:Infinity}
function cartLines(){return products.map(product=>({product,quantity:cartQuantity(product.id)})).filter(line=>line.quantity>0)}
function cartNotice(message){const existing=document.querySelector('#cart-notice');if(existing){existing.textContent=message;return}document.querySelector('.page-title')?.insertAdjacentHTML('afterend',`<p id="cart-notice" class="form-result error">${message}</p>`)}
function removeFromCart(id){cart=cart.filter(item=>item!==id);save();render()}
function updateCartQuantity(id,quantity){const product=products.find(item=>item.id===id);const maximum=availableQuantity(product);const next=Math.max(0,Math.min(Number(quantity)||0,maximum));if(next===0)return removeFromCart(id);cart=cart.filter(item=>item!==id);cart.push(...Array(next).fill(id));save();render()}
function add(id){const product=products.find(item=>item.id===id);if(!product||!product.inStock)return cartNotice('Ce produit n’est plus disponible.');const current=cartQuantity(id);const maximum=availableQuantity(product);if(current>=maximum)return cartNotice(`Quantité maximale disponible : ${maximum}.`);cart.push(id);save();render()}
function cartPage(){const lines=cartLines();const total=lines.reduce((sum,line)=>sum+line.product.price*line.quantity,0);return `<main class="shell inner"><div class="crumb">Accueil / Panier</div><h1 class="page-title">Votre panier</h1>${lines.length?`<div class="cart-layout"><div>${lines.map(({product,quantity})=>`<div class="cart-item"><img src="${product.img}" alt="${product.name}"><div class="cart-item-details"><div class="product-cat">${product.state} · ${product.cat}</div><h3 style="margin:6px 0;font:600 19px 'Space Grotesk'">${product.name}</h3><div class="specs">${product.spec}</div><b style="display:block;margin-top:13px">${money(product.price)}</b><div class="cart-controls"><div class="quantity" aria-label="Quantité de ${product.name}"><button type="button" onclick="updateCartQuantity(${product.id},${quantity-1})" aria-label="Réduire la quantité">−</button><span>${quantity}</span><button type="button" onclick="updateCartQuantity(${product.id},${quantity+1})" ${quantity>=availableQuantity(product)?'disabled':''} aria-label="Augmenter la quantité">+</button></div><button class="cart-remove" type="button" onclick="removeFromCart(${product.id})">Retirer</button></div>${product.stockQuantity!==null?`<small class="stock-note">${product.stockQuantity} disponible${product.stockQuantity>1?'s':''}</small>`:''}</div></div>`).join('')}</div><aside class="summary"><h3>Récapitulatif</h3><div><span>Sous-total</span><span>${money(total)}</span></div><div><span>Livraison à domicile</span><span>${money(HOME_DELIVERY)}</span></div><div class="total"><span>Total livraison incluse</span><span>${money(total+HOME_DELIVERY)}</span></div><p class="specs">Retrait en boutique OKOUMÉ : gratuit.</p><a class="btn" href="#/connexion">Passer la commande&nbsp; →</a></aside></div>`:`<div class="empty"><p>Votre panier est vide.</p><a class="btn" href="#/catalogue">Découvrir la boutique</a></div>`}</main>`}
checkout=async function(event){event.preventDefault();const lines=cartLines();if(!lines.length)return go('/catalogue');const unavailable=lines.find(line=>!line.product.inStock||line.quantity>availableQuantity(line.product));if(unavailable){cartNotice(`« ${unavailable.product.name} » n’est plus disponible dans la quantité demandée.`);return go('/panier')}const user=JSON.parse(sessionStorage.getItem('okoumeUser')||'{}');const body={items:lines.map(line=>({id:line.product.id,quantity:line.quantity})),delivery_method:delivery.value,payment_method:paymentMethod.value,billing:{first_name:firstName.value,last_name:lastName.value,email:user.email||'',phone:phone.value,address_1:address.value,city:delivery.value==='home'?'Livraison à domicile':'Retrait OKOUMÉ'}};showLoader('Vérification du stock…');try{const r=await fetch(`${apiRoot}/wp-json/okoume/v1/orders`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message||'La commande n’a pas pu être créée.');sessionStorage.setItem('okoumeOrder',data.number);sessionStorage.setItem('okoumeOrderTotal',data.total);sessionStorage.setItem('okoumePaymentMethod',paymentMethod.value);cart=[];save();if(data.redirect_url){location.href=data.redirect_url;return}go('/confirmation')}catch(error){alert(error.message);if(error.message.includes('Stock')||error.message.includes('disponible'))go('/panier')}finally{hideLoader()}}

/* Product page: gallery is one grid column; the purchase information is the other. */
const productQuantities={};
function productQuantity(id){return productQuantities[id]||1}
function setProductQuantity(id,next){const product=products.find(item=>item.id===id);const quantity=Math.max(1,Math.min(Number(next)||1,availableQuantity(product)));productQuantities[id]=quantity;const value=document.querySelector('#product-quantity-value');if(value)value.textContent=quantity;const increase=document.querySelector('#product-quantity-increase');if(increase)increase.disabled=quantity>=availableQuantity(product)}
product=function(id){if(!products.length)return `<main class="shell inner"><div class="product-skeleton" aria-label="Chargement du produit"><i></i><div><i></i><i></i><i></i><i></i></div></div></main>`;const p=products.find(item=>item.id===+id);if(!p)return `<main class="shell inner"><div class="empty"><p>Ce produit n’est plus disponible.</p><a class="btn" href="#/catalogue">Retour à la boutique</a></div></main>`;const defects=p.defects&&p.defects!=='Aucun défaut notable'?`<section class="known-defects"><b>Défauts connus</b><p>${p.defects}</p></section>`:'';return `<main class="shell inner"><div class="crumb"><a href="#/">Accueil</a> / <a href="#/catalogue">Boutique</a> / ${p.name}</div><div class="product-detail"><section class="gallery-column"><div class="gallery-main"><img src="${p.img}" alt="${p.name}"><span class="badge ${p.state==='NEUF'?'good':''}">${p.state}</span></div></section><section class="purchase-column"><div class="product-cat">${p.cat}</div><h1>${p.name}</h1><p class="specs product-spec" style="font-size:15px">${p.spec}</p><div class="detail-price">${money(p.price)}</div><div class="status">${p.inStock?'✓ En stock · Contrôlé par OKOUMÉ':'Indisponible · Alerte de retour disponible'}</div>${defects}<div class="quantity product-quantity" aria-label="Quantité"><button type="button" onclick="setProductQuantity(${p.id},productQuantity(${p.id})-1)" aria-label="Réduire la quantité">−</button><span id="product-quantity-value">${productQuantity(p.id)}</span><button type="button" id="product-quantity-increase" onclick="setProductQuantity(${p.id},productQuantity(${p.id})+1)" ${productQuantity(p.id)>=availableQuantity(p)?'disabled':''} aria-label="Augmenter la quantité">+</button></div><button class="btn" onclick="add(${p.id},productQuantity(${p.id}))">Ajouter au panier&nbsp; →</button><div class="detail-list"><div><span>État</span><b>${p.state}</b></div><div><span>Stockage</span><b>${p.storage||'—'}</b></div><div><span>Couleur</span><b>${p.color||'—'}</b></div>${p.battery?`<div><span>Batterie</span><b>${p.battery}</b></div>`:''}<div><span>Garantie OKOUMÉ</span><b>${p.warranty||'À confirmer'}</b></div><div><span>Accessoires</span><b>${p.accessories||'Non renseignés'}</b></div><div><span>Contrôles techniques</span><b>${p.controls||'Non renseignés'}</b></div></div></section></div></main>`}
function positionProductTrust(){const detail=document.querySelector('.purchase-column');const price=detail?.querySelector('.detail-price');const trust=detail?.querySelector('[data-trust="product"]');if(detail&&price&&trust&&price.nextElementSibling!==trust)price.insertAdjacentElement('afterend',trust)}
new MutationObserver(positionProductTrust).observe(document.querySelector('#app'),{childList:true,subtree:true});

function openAddedToCart(product){document.querySelector('#added-to-cart-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="added-to-cart-modal" class="cart-modal-backdrop" role="presentation"><section class="cart-modal" role="dialog" aria-modal="true" aria-labelledby="added-to-cart-title"><button class="cart-modal-close" type="button" aria-label="Fermer">×</button><div class="cart-modal-check">✓</div><h2 id="added-to-cart-title">Produit ajouté au panier</h2><p><b>${product.name}</b><br>${cart.length} article${cart.length>1?'s':''} dans votre panier.</p><div class="cart-modal-actions"><button class="btn ghost cart-modal-continue" type="button">Continuer mes achats</button><a class="btn" href="#/panier">Voir mon panier&nbsp; →</a></div></section></div>`);const modal=document.querySelector('#added-to-cart-modal');const close=()=>modal.remove();modal.querySelector('.cart-modal-close').addEventListener('click',close);modal.querySelector('.cart-modal-continue').addEventListener('click',close);modal.addEventListener('click',event=>{if(event.target===modal)close()});document.addEventListener('keydown',function escape(event){if(event.key==='Escape'){close();document.removeEventListener('keydown',escape)}});modal.querySelector('.cart-modal-continue').focus()}
add=function(id,quantity=1){const product=products.find(item=>item.id===id);if(!product||!product.inStock)return cartNotice('Ce produit n’est plus disponible.');const current=cartQuantity(id);const maximum=availableQuantity(product);const requested=Math.max(1,Number(quantity)||1);if(current+requested>maximum){cartNotice(`Quantité maximale disponible : ${maximum}.`);return}cart.push(...Array(requested).fill(id));save();render();openAddedToCart(product)};
function mountAvailabilityForProductLayout(){const path=location.hash.slice(1)||'/';if(!path.startsWith('/produit/'))return;const current=products.find(item=>item.id===+path.split('/').pop());const detail=document.querySelector('.purchase-column');if(!current||!detail||current.inStock||detail.querySelector('.restock-box'))return;const status=detail.querySelector('.status');if(status){status.textContent='Indisponible · Alerte de retour disponible';status.classList.add('stock-out-status')}detail.querySelector('.product-quantity')?.remove();const buy=detail.querySelector('button.btn');if(buy)buy.replaceWith(document.createRange().createContextualFragment(restockMarkup(current)))}
new MutationObserver(mountAvailabilityForProductLayout).observe(document.querySelector('#app'),{childList:true,subtree:true});
